#!/bin/bash
# qemu-img create -f raw win10.img 100G
# qemu-img create -f qcow2 Gentoo-VM.img 100G

function start(){
exec qemu-system-x86_64 -enable-kvm \
     -cpu host \
     -drive file=T2SDE-VM.img,if=virtio \
     -netdev user,id=vmnic,hostname=T2SDE-VM \
     -device virtio-rng-pci \
     -m 10240M \
     -smp 8 \
     -monitor stdio \
     -name "T2SDE" \
     -boot d \
     -cdrom x86-64.iso \
     -net nic \
     -net tap,id=tap1
#-net tap,ifname=tap0,script=no,downscript=no \
    #-device e1000,netdev=network0,mac=52:55:00:d1:55:01 \
    #-netdev tap,id=network0,ifname=wlan0,script=no,downscript=no
#-net nic -net tap,ifname=kvmnat \
    #-net nic,vlan=0,model=virtio,macaddr=00:16:35:AF:94:4B \
    #-net tap,vlan=0,ifname=$tap,script=no,downscript=no \
}

start &
sleep 2
